services:
  due-postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - due-postgres-data:/var/lib/postgresql/data
    networks:
      - networkName

volumes:
  due-postgres-data: {}

networks:
  networkName:
    name: due-network